networks:
  competencenetworkapi:
services:
  competenceplataform.database:
      image: mcr.microsoft.com/mssql/server:2022-latest
      container_name: "competenceplataform.database"
      volumes:
      - sqlserver_data:/var/opt/mssql
      ports:
        - "1433:1433"
      environment:
       - ACCEPT_EULA=Y
       - MSSQL_SA_PASSWORD=MyPassword*1234
      networks:
        - competencenetworkapi
  competenceplatform.api:
    image: ${DOCKER_REGISTRY-}competenceplatformapi
    container_name: "competenceplatform.api"
    build:
      context: .
      dockerfile: src/CompetencePlatform.API/Dockerfile
    networks:
        - competencenetworkapi
    depends_on:
        - competenceplataform.database
    ports:
     - "5000:5000"
     - "5001:5001"
volumes:
  sqlserver_data:  
     
